version: '3.8'

services:
  mysql-event:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${EVENT_DB_PASSWORD}
      MYSQL_DATABASE: event_db
    ports:
      - "3308:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5674:5672"
      - "15674:15672"

  eureka:
    image: your-eureka-image
    environment:
      EUREKA_SERVER_PORT: 8763
    ports:
      - "8763:8761"

  event-service:
    build: ./event-service
    environment:
      - DB_URL=jdbc:mysql://mysql-event:3306/event_db
      - DB_USER=${EVENT_DB_USER}
      - DB_PASSWORD=${EVENT_DB_PASSWORD}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - EUREKA_URL=http://eureka:8763/eureka/
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mysql-event
      - rabbitmq
      - eureka
    ports:
      - "8084:8084"