version: '3.8'

services:
  mysql-auth:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: auth_db
    ports:
      - "3310:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5676:5672"
      - "15676:15672"

  eureka:
    image: your-eureka-image
    environment:
      EUREKA_SERVER_PORT: 8765
    ports:
      - "8765:8761"

  auth-service:
    build: ./auth-service
    environment:
      - DB_URL=jdbc:mysql://mysql-auth:3306/auth_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - EUREKA_URL=http://eureka:8765/eureka/
    depends_on:
      - mysql-auth
      - rabbitmq
      - eureka
    ports:
      - "8086:8086"