version: '3.8'

services:
  mysql-booking:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: booking_db
    ports:
      - "3309:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5675:5672"
      - "15675:15672"

  eureka:
    image: your-eureka-image
    environment:
      EUREKA_SERVER_PORT: 8764
    ports:
      - "8764:8761"

  booking-service:
    build: ./booking-service
    environment:
      - DB_URL=jdbc:mysql://mysql-booking:3306/booking_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - EUREKA_URL=http://eureka:8764/eureka/
    depends_on:
      - mysql-booking
      - rabbitmq
      - eureka
    ports:
      - "8085:8085"