version: '3.8'

services:
  mysql-notification:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      MYSQL_DATABASE: notification_db
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"

  eureka:
    image: your-eureka-image
    environment:
      EUREKA_SERVER_PORT: 8762
    ports:
      - "8762:8761"

  notification-service:
    build: ./notification-service
    environment:
      - DB_URL=jdbc:mysql://mysql-notification:3306/notification_db
      - DB_USER=${NOTIFICATION_DB_USER}
      - DB_PASSWORD=${NOTIFICATION_DB_PASSWORD}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - EUREKA_URL=http://eureka:8762/eureka/
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PROPERTIES_MAIL_SMTP_AUTH=${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
    depends_on:
      - mysql-notification
      - rabbitmq
      - eureka
    ports:
      - "8083:8083"